package gazelle

import (
	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/rule"
	"github.com/emirpasic/gods/sets/treeset"
	godsutils "github.com/emirpasic/gods/utils"
)

// targetBuilder builds targets to be generated by Gazelle.
type targetBuilder struct {
	kind         string
	name         string
	bzlPackage   string
	srcs         *treeset.Set
	deps         *treeset.Set
	resolvedDeps *treeset.Set
}

// newTargetBuilder constructs a new targetBuilder.
func newTargetBuilder(kind, name, bzlPackage string) *targetBuilder {
	return &targetBuilder{
		kind:         kind,
		name:         name,
		bzlPackage:   bzlPackage,
		srcs:         treeset.NewWith(godsutils.StringComparator),
		deps:         treeset.NewWith(moduleComparator),
		resolvedDeps: treeset.NewWith(godsutils.StringComparator),
	}
}

// addSrcs copies all values from the provided srcs to the target.
func (t *targetBuilder) addSrcs(srcs *treeset.Set) *targetBuilder {
	it := srcs.Iterator()
	for it.Next() {
		t.srcs.Add(it.Value().(string))
	}
	return t
}

// addModuleDependencies copies all values from the provided deps to the target.
func (t *targetBuilder) addModuleDependencies(deps *treeset.Set) *targetBuilder {
	it := deps.Iterator()
	for it.Next() {
		t.deps.Add(it.Value().(ImportStatement))
	}
	return t
}

// build returns the assembled *rule.Rule for the target.
func (t *targetBuilder) build() *rule.Rule {
	r := rule.NewRule(t.kind, t.name)
	if !t.srcs.Empty() {
		r.SetAttr("srcs", t.srcs.Values())
	}
	if !t.deps.Empty() {
		r.SetPrivateAttr(config.GazelleImportsKey, t.deps)
	}
	r.SetPrivateAttr(resolvedDepsKey, t.resolvedDeps)
	return r
}

// ImportStatement represents a path imported from a source file.
// Imports can be of any form (es6, cjs, amd, ...).
// Imports may be relative ot the source, absolute, workspace, named modules etc.
type ImportStatement struct {
	// The TypeScript module name as seen on import statements.
	Path string `json:"path"`
	// The line number where the import happened.
	SourceLineNumber uint32 `json:"sourcelineno"`
	// The path of the file containing the import
	SourcePath string `json:"sourcepath"`
}

// moduleComparator compares modules by name.
func moduleComparator(a, b interface{}) int {
	return godsutils.StringComparator(a.(ImportStatement).Path, b.(ImportStatement).Path)
}
